WIP feature/lesson_2
vBrusentsov/ma-nodejs-2021 pull request #2
Opened 2021-11-10 11:16 UTC by vBrusentsov

2021-11-15 19:13 UTC, VitaliiHurin requested changes

2021-11-15 19:13 UTC, VitaliiHurin commented on src/services/index.js
> +}
Це можна було б просто константами зробити. 🙂
Функція тут зайва.

2021-11-15 19:13 UTC, VitaliiHurin commented on src/server/controllers.js
> +  if (validateParams(params) === false) {
Можна не робити явну перевірку `=== false`, краще б просто `if (!validateParams(params)) {`

2021-11-15 19:13 UTC, VitaliiHurin commented on src/server/controllers.js
> +    codeNoContent,
Назви не дуже відповідні. Якщо є `codeNoContent`, то чому тоді є просто `code`? 🙂
Як я зазначив, це краще б константами визначити. Або ще можна витягнути все з стандратного модуля http:
[https://nodejs.org/api/http.html#http_http_status_codes](https://nodejs.org/api/http.html#http_http_status_codes)

2021-11-15 19:13 UTC, VitaliiHurin commented on src/server/controllers.js
> +  } else {
Загальна рекомендація – робити менше вкладеностей коду, коли це можливо.
В даному випадку цю конструкцію
> if (...) {
>    ...
> } else {
>    ...
> }

краще замінити такою:

> if (...) {
>    ...
>    return;
> }
> ...

2021-11-15 19:13 UTC, VitaliiHurin commented on src/server/controllers.js
> +  } else {
Взагалі є теорія, що можна практично завжди писати без `else`. 🙂

2021-11-15 19:13 UTC, VitaliiHurin commented on src/server/controllers.js
> +    req.body !== undefined &&
Тут теж явні перевірки зайві.

2021-11-15 19:13 UTC, VitaliiHurin commented on src/server/controllers.js
> +    return;
Ось тут добре з `return`! 🙂

2021-11-15 19:13 UTC, VitaliiHurin commented on src/index.js
> +const PORT = 3000;
Константу порта можна винести в окремий файл конфігу. 🙂

2021-11-15 19:13 UTC, VitaliiHurin commented on src/server/controllers.js
> +    path.resolve(process.cwd(), './LESSON_1/src/data.json'),
Старий шлях. 🙂
Шлях краще теж винести в констансу і в конфіг.

2021-11-15 19:13 UTC, VitaliiHurin commented on src/server/controllers.js
> +  fs.writeFileSync(
Роботу з файловою системою бажано огорнути в try catch блок.

2021-11-15 19:13 UTC, VitaliiHurin commented on src/server/controllers.js
> +      !(
Оце не дуже страшнувата умова, особливо з `!(`. 😁 Можливо можна відрефакторити щоб було більш зручно для сприйняття?

2021-11-15 19:13 UTC, VitaliiHurin commented on src/server/controllers.js
> +    (products) =>
Можна використати деструктуризацію тут для полів об'єкту products.

2021-11-15 19:13 UTC, VitaliiHurin commented on src/server/controllers.js
> +            typeof products.quantity === 'number') &&
Тут точно нічого не з'їхало по відступах?

2021-11-15 19:13 UTC, VitaliiHurin commented on src/server/controllers.js
> +    (!!params.pricePerKilo &&
Для чого тут подвійний `!!`? Можна просто перевіряти без цього. 🙂

2021-11-15 19:13 UTC, VitaliiHurin commented on src/server/routes.js
> +    });
Що робить цей код?

2021-11-15 19:13 UTC, VitaliiHurin commented on src/server/routes.js
> +    return controllers.getResultMostExpensive(req, res, req.body);
Звідки взявся третій аргумент?

2021-11-15 19:13 UTC, VitaliiHurin commented on src/server/routes.js
> +    return controllers.getResultPrice(req, res, req.body);
Тут теж третій аргумент...

2021-11-16 19:20 UTC, vBrusentsov commented on src/index.js
> +const PORT = 3000;
Дякую винів в окрему папку в src в файл index.js

2021-11-16 19:22 UTC, vBrusentsov commented on src/server/controllers.js
> +    codeNoContent,
Дякую, я перейменував в всьому коді code на codeGood

2021-11-16 19:23 UTC, vBrusentsov commented on src/server/controllers.js
> +  if (validateParams(params) === false) {
Змінив це, та перевірив все запрацювало. Дякую за пораду

2021-11-16 19:25 UTC, vBrusentsov commented on src/server/controllers.js
> +  } else {
Дякую, замінив це у всьому коді та буду надалі намагатись використовувати рекомендовану тобою конструкцію.

2021-11-16 19:26 UTC, vBrusentsov commented on src/server/controllers.js
> +    req.body !== undefined &&
Дякую, виправив.

2021-11-16 19:28 UTC, vBrusentsov commented on src/server/controllers.js
> +    path.resolve(process.cwd(), './LESSON_1/src/data.json'),
Дякую, виправив. Та перемістив в config/index.js

2021-11-16 19:30 UTC, vBrusentsov commented on src/server/controllers.js
> +            typeof products.quantity === 'number') &&
З відступом мені допоміг prittier

2021-11-16 19:32 UTC, vBrusentsov commented on src/server/controllers.js
> +    (!!params.pricePerKilo &&
Дякую, я виправив. Подумав, що без !! поверне undefined, а не boolean

2021-11-16 19:42 UTC, vBrusentsov commented on src/server/routes.js
> +    });
Цей код приймає post- запит, перебирає ключі та значення і записує в об'єкт.

2021-11-16 19:42 UTC, vBrusentsov commented on src/services/index.js
> +}
Дякую, я переробив із функцій в константу

2021-11-16 19:58 UTC, VitaliiHurin commented on src/server/controllers.js
> +    codeNoContent,
Краще може по назві коду як він в стандарті називається? `200 OK`, тому мабуть codeOk краще. 🙂

2021-11-16 21:54 UTC, vBrusentsov commented on src/server/routes.js
> +    return controllers.getResultMostExpensive(req, res, req.body);
Аргумент видалив))

2021-11-16 21:55 UTC, vBrusentsov commented on src/server/routes.js
> +    return controllers.getResultPrice(req, res, req.body);
І тут також видалив аргумент зайвий

2021-11-16 21:55 UTC, vBrusentsov commented on src/server/controllers.js
> +    codeNoContent,
Я перейменував

2021-11-16 21:56 UTC, vBrusentsov commented on src/server/controllers.js
> +  fs.writeFileSync(
Використав блок try catch, дякую

2021-11-17 19:58 UTC, vBrusentsov commented on src/server/controllers.js
> +      !(
Інвертував логіку. Дякую

2021-11-17 19:59 UTC, vBrusentsov commented on src/server/controllers.js
> +    (products) =>
Дякую виконав деструктуризацію

2021-11-18 19:51 UTC, VitaliiHurin requested changes

2021-11-18 19:51 UTC, VitaliiHurin commented on src/server/controllers.js
> +    res.end(JSON.stringify({ err }));
Користувачу краще не видавати стек і подробиці помилок. Це погана практика, яка розкриває нутрощі назовні, роблячи код вразливим до атак. Тут треба віддати коректний код і загальний опис помилки без подробиць.

2021-11-18 19:51 UTC, VitaliiHurin commented on src/services/index.js
> +  goods,
Чому товари в об'єкті codes поблизу з меседжами і кодами. Краще окремо це експортувати просто, бо взагалі не логічно в об'єкті з назвою codes навіть і меседжі зберігати. 🙂

2021-11-18 20:28 UTC, vBrusentsov commented on src/server/controllers.js
> +    res.end(JSON.stringify({ err }));
Дякую, я вже виправив

2021-11-18 20:29 UTC, vBrusentsov commented on src/services/index.js
> +  goods,
Дякую, я видалив массив товарів з індексу, так як я побачив що рекаваєрити краще в контролер

2021-11-18 20:44 UTC, merged