Feature/homework_3
vBrusentsov/ma-nodejs-2021 pull request #4
Opened 2021-11-29 19:28 UTC by vBrusentsov

2021-11-29 19:50 UTC, VitaliiHurin requested changes

2021-11-29 19:50 UTC, VitaliiHurin commented on src/server/controllers.js
> +          const discountProducts = {
Тут один продукт, тому назву краще змінити на однину.

2021-11-29 19:50 UTC, VitaliiHurin commented on src/server/controllers.js
> +const util = require('util');
Зазвичай деструктуризацією лише один promisify імпортують

2021-11-29 19:50 UTC, VitaliiHurin commented on src/server/controllers.js
> +function retryPromises(fn, ms = 0) {
Чому це теж множина? Щось я запутався... 🤔

2021-11-29 19:50 UTC, VitaliiHurin commented on src/server/controllers.js
> +        }, ms);
Жостка реалізація трохи 😁

2021-11-29 19:50 UTC, VitaliiHurin commented on src/server/controllers.js
> +      res.write(JSON.stringify(promisesDiscount.then(), err));
🤔 Тут точно все так?

2021-11-29 19:50 UTC, VitaliiHurin commented on src/server/controllers.js
> +    });
А де тут .catch() ?

2021-11-29 19:50 UTC, VitaliiHurin commented on src/server/controllers.js
> +      res.write(JSON.stringify(goodsWithPrice, err));
Чому тут ОК код?

2021-11-29 19:50 UTC, VitaliiHurin commented on src/server/controllers.js
> +    return promisifyCallback().then((value) => {
Оце ж треба тут через async дістати. 🙂

2021-11-29 19:50 UTC, VitaliiHurin commented on src/server/controllers.js
> +    res.end(JSON.stringify(asyncDiscount.then(), err));
Те ж саме і тут. Щось не дуже я зрозумів таку обробку помилки...

2021-11-29 19:57 UTC, vBrusentsov commented on src/server/controllers.js
> +          const discountProducts = {
А множина томущо там можить бути в body  декілька елементів масиву тому у всьому коді я назвав об'єкт саме так.

2021-11-29 19:58 UTC, vBrusentsov commented on src/server/controllers.js
> +const util = require('util');
В прикладі побачив що так було та виріши повторити.

2021-11-29 19:59 UTC, vBrusentsov commented on src/server/controllers.js
> +function retryPromises(fn, ms = 0) {
Також елементи масиву приходять))

2021-11-29 20:00 UTC, vBrusentsov commented on src/server/controllers.js
> +      res.write(JSON.stringify(promisesDiscount.then(), err));
Я видалю зен він тут лишній, попробувати такк реалізувати.

2021-12-05 14:55 UTC, VitaliiHurin requested changes

2021-12-05 14:55 UTC, VitaliiHurin commented on src/services/index.js
>      const promisifyCallback = util.promisify(discountPriceCallback);
Це краще зробити один раз, ніж для кожної ітерації в циклі. І знову не ясно чому називається Callback змінна, якщо це вже проміс. 🙂

2021-12-05 14:55 UTC, VitaliiHurin commented on src/services/index.js
> +            discount = product.price * ((100 - value * 3) / 100);
Не можна згенероване значення просто помножувати на 3, бо це ж може бути більше 100 і тоді ціна стане від'ємною. 🙂 Тут можна або тричі генерувати знижку і поетапно застосовувати її до ціни, або вже один раз згенерувати і тричі підряд застосувати.
Ідея в тому, що якщо, наприклад, знижка 35%, а ціна 10, то після застосування потрійної знижки матимемо ціну 10 * 0,65 * 0,65 * 0,65 = 2,74625.

2021-12-05 15:07 UTC, vBrusentsov commented on src/server/controllers.js
> +        }, ms);
А що тут жосткого

2021-12-05 15:08 UTC, vBrusentsov commented on src/server/controllers.js
> +      res.write(JSON.stringify(goodsWithPrice, err));
Змінив на вірний статус код

2021-12-05 15:09 UTC, vBrusentsov commented on src/server/controllers.js
> +    res.end(JSON.stringify(asyncDiscount.then(), err));
видалив Зен

2021-12-05 15:09 UTC, VitaliiHurin commented on src/server/controllers.js
> +        }, ms);
Ну екстравагантне рішення трохи, але ок 😄

2021-12-05 15:14 UTC, vBrusentsov commented on src/server/controllers.js
> +    });
Додав кетч

2021-12-05 15:16 UTC, vBrusentsov commented on src/server/controllers.js
> +    return promisifyCallback().then((value) => {
А там в завданні було вказано що якщо використовувати метод промізіфай то асинк не можа

2021-12-05 15:21 UTC, VitaliiHurin requested changes

2021-12-05 15:21 UTC, VitaliiHurin commented on src/server/controllers.js
> +    return promisifyCallback().then((value) => {
Так це ж метод getAsyncDiscountPrice...

2021-12-05 15:49 UTC, vBrusentsov commented on src/services/index.js
> +            discount = product.price * ((100 - value * 3) / 100);
Я переробив логіку з скидкою

2021-12-05 15:58 UTC, vBrusentsov commented on src/services/index.js
>      const promisifyCallback = util.promisify(discountPriceCallback);
Я змінив назву функції, але циелом я не знаю

2021-12-06 11:46 UTC, VitaliiHurin approved these changes

2021-12-06 18:57 UTC, vBrusentsov commented
Я перемістив промисифай

2021-12-06 18:57 UTC, merged